server:
  port: 8081
#mybatis
mybatis:
  mapperLocations: classpath:mapping/*.xml
#DB Configuration
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    name: seacms
    url: jdbc:mysql://localhost:3306/seacms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#logging
logging:
  level:
    com.xc.springboot: debug